version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: simple_chat_db
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=simple_chat

